### ISSUE TITLE
CSS追加 FireFoxのリンク選択時の点線を消す

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#100]
Firefoxのリンクの点線いつも消してるので。CSS追加してくださいー

a:link,
a:visited,
a:active,
a:hover {
    overflow: hidden;
    outline: none;
}

**Comment by inc2734** [comment]
アクセシビリティ的には outline は消さないほうが良いと思うのですが結構気になります？
http://white-stage.com/article.php/outline

**Comment by mignonstyle** [comment]
テキストリンクはあまり気にならないのですが、グロナビとかボタンのところにつくのが気になって…。
皆さんはどうされてますか？
アクセシビリティ的に消さないほうがいいという事でしたらこのままか、CSSでちょっと見た目を変更するかでしょうか。

**Comment by mayukojpn** [comment]
FIreFox ですか？いまみたけど線出ず。38.0.1 です。

**Comment by mignonstyle** [comment]
ありがとうございます！ではいったんこのままでCloseで。気になったらアクセシビリティに配慮してCSSで見た目を変更する方向にしますね。
