### ISSUE TITLE
Twitterのアイコン作成 Bashわぷー

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#111]
プロフィール画像（アイコン）のサイズ：400ピクセル×400ピクセル

**Comment by mayukojpn** [comment]
SVG のアウトライン化していざ保存という時に、アプリの Sketch がコケました......orz
今日帰ってきたらやりますのでおまちください

**Comment by mayukojpn** [comment]
ほい！これでどうでしょう。背景もあったほうがいい？？![twitter](https://cloud.githubusercontent.com/assets/1886443/11975343/22228b30-a9b0-11e5-9912-e73b3109fcdc.png)

**Comment by mignonstyle** [comment]
@mayukojpn 背景もつけてほしいですー。森山さん作業できそうです？

**Comment by mayukojpn** [comment]
うーんこんなかんじでしょうか？けっこうむずい.....
![twitter 2](https://cloud.githubusercontent.com/assets/1886443/11979591/f265939c-a9d7-11e5-8cec-8d381241a8b4.png)
![twitter 3](https://cloud.githubusercontent.com/assets/1886443/11979593/f4144bb6-a9d7-11e5-8cb6-b4456ed89afd.png)

**Comment by mignonstyle** [comment]
まゆこさんごめんなさい！お返事なかったので、私のほうで作業しちゃいました！

![wapuu](https://cloud.githubusercontent.com/assets/7196028/11979799/8b147a8a-a9d9-11e5-95de-0c31b95ec97b.jpg)

**Comment by contiki9** [comment]
@mayukojpn  
mignonstyleさんのほうが明るく楽しげな印象持ちましたのでこちらを採用しますね。
せっかく作業頂いたのにすいません。

**Comment by mignonstyle** [comment]
せっかく作ってくださったのにすみませんー

**Comment by mignonstyle** [comment]
Fix

![twitter_wapuu](https://cloud.githubusercontent.com/assets/7196028/11984691/bb59d808-aa00-11e5-8272-5901cf40a677.png)
