### ISSUE TITLE
faviconが表示されていない

### ISSUE THREAD

**Issue by contiki9** [WordBash/kyoto-vol1#118]
どなたか原因わかります？
多分リンク切れとかでないと思うのですが…

**Comment by hideokamoto** [comment]
404なのでファイルが上がってないのかも。

**Comment by hideokamoto** [comment]
うん、ない。
https://github.com/WordBash/kyoto-vol1/tree/gh-pages

ビルドスクリプト直せばいいかな。

**Comment by torounit** [comment]
そうですね。なおしますー。

**Comment by hideokamoto** [comment]
オナシャス！
