### ISSUE TITLE
コミュニティバッジは運営者ですよ。

### ISSUE THREAD

**Issue by mayukojpn** [WordBash/kyoto-vol1#128]
メンバー？
なんかこだわりがあるのかな？すいません。でもメンバーだと間違ってる気がします。

**Comment by torounit** [comment]
正 コミュニティ運営者
誤 コミュニティメンバー
ってことですか？

合ってるのかわからないですが・・・・。

**Comment by mayukojpn** [comment]
そう、そうですー。
もしくは、コアと合わせて「WordPress 勉強会運営者」とするか。どちらがわかりやすいでしょう？

**Comment by torounit** [comment]
必ずしも勉強会って訳じゃ無い気がするので、「コミュニティ運営者」のほうがニュアンスは近いと思いますけど、どうなんでしょうか？

**Comment by mayukojpn** [comment]
飲み会のばあいもありますものね。
おこのみでおねがいします！

**Comment by contiki9** [comment]
「コミュニティ運営者」にしましょうか。

**Comment by hideokamoto** [comment]
日本向けだと「コミュニティ運営者」が伝わりやすいかなと思います。

**Comment by torounit** [comment]
@mayukojpn ちなみに、変更箇所もう1カ所あるんです。クソ実装ですみません。。。。。。。

**Comment by mayukojpn** [comment]
うおお、みんなみてたのね。
ちなみに厳密に言うと、チームのバッジなので、「なになにをした人」ではないんですよねえ。でもこのほうがわかりやすいからいいと思います🙆

**Comment by torounit** [comment]
https://www.facebook.com/groups/wordbash/permalink/1117487634958462/
