### ISSUE TITLE
SNSでシェアされる時の文言変更

### ISSUE THREAD

**Issue by contiki9** [WordBash/kyoto-vol1#139]

**Comment by contiki9** [comment]
下記の用に修正。日付と開催地域の追加
【京都開催】1/23（土）13：30~　WordBash Kyoto vol.1

**Comment by torounit** [comment]
<img width="821" alt="2015-12-24 16 49 29" src="https://cloud.githubusercontent.com/assets/1908815/11991496/6bc7099c-aa5e-11e5-9534-cf1b8668b44a.png">
<img width="606" alt="2015-12-24 16 49 56" src="https://cloud.githubusercontent.com/assets/1908815/11991497/6bd1d5de-aa5e-11e5-8b63-7480d56f2936.png">
