### ISSUE TITLE
【SP】テキストのセンタリング

### ISSUE THREAD

**Issue by inc2734** [WordBash/kyoto-vol1#142]
ABOUT や CONTENT は文字数が多いのでスマホのときは左揃えのほうが読みやすそうと思ったのですがどうでしょう？

**Comment by mignonstyle** [comment]
そのほうが読みやすいですねー。修正お願いできますか？

**Comment by inc2734** [comment]
了解です！後ほど修正します。

PCのミドル幅のときも改行が気になりますね…。

![2015-12-24 8 51 50](https://cloud.githubusercontent.com/assets/1094306/11987049/a40aa068-aa1b-11e5-9026-a49c1efcca8c.png)

**Comment by mignonstyle** [comment]
ありがとうございます！
中揃えの改行位置はずっと気になってて、#61【PC】【TB】【SP】改行位置の変更を入れる （visible-xs-blockとか）でissues立ててます。

後ほどでいいので、キタジマさんのほうで気になる所を直してもらってもいいでしょうか？

**Comment by mignonstyle** [comment]
いっそのこと左揃えにしちゃったほうがきれいかも

**Comment by inc2734** [comment]
人物紹介が左揃えなので、読んだときに揃ってなかったのがちょっと違和感があって。とりあえず左揃えにしてみますので、おかしかったらまた書き込んでください！

**Comment by inc2734** [comment]
むむ、改行も調整しないと左によりすぎるように見えることもありますね。改行必要ですかね？

**Comment by mignonstyle** [comment]
左揃えにするなら改行なくてもいいかもですよね。
いったんキタジマさんが読みやすいと思うように直して頂いていいですか？

**Comment by inc2734** [comment]
@mignonstyle 確認おねがいします！ https://github.com/WordBash/kyoto-vol1/tree/issues/%23142

**Comment by mignonstyle** [comment]
ありがとうございます！やっぱりスマホとかだと左揃えのほうが見やすいですねー :）

すみませんが、CONTENTの3つ目
「味の薄いセッションは抜けて良い自由な空間」の箇所の文章が中揃えのままのようです。
お手数ですがご確認お願いしますー

あと、ついでと言ってはなんですが、
ABOUT WORDBASHの「 聞きたい事を経験者に聞ける」「自分と同じ悩みを抱えた人繋がれる」のところに改行入れて

「 聞きたい事を経験者に聞ける」
「自分と同じ悩みを抱えた人繋がれる」

というふうに修正していただいてもよろしいでしょうか？
上記2点修正していただいたらマージしちゃって大丈夫ですのでよろしくお願いしますー
