### ISSUE TITLE
オレにもしゃべらせろ！

### ISSUE THREAD

**Issue by ixkaito** [WordBash/kyoto-vol1#146]

**Comment by torounit** [comment]
+1

**Comment by mayukojpn** [comment]
+1

**Comment by inc2734** [comment]
プロフィール部分にプロフィールの追加と、参加したいセッションのとこにプルリクください！

**Comment by inc2734** [comment]
すみません、先走りました。サイトへの追加は無しでした！当日はギャラリーの方も交えて話しやすい感じにしたいとか構想中です。

**Comment by hideokamoto** [comment]
スケジュールかなりギリギリな感じなので、
話を振るようなことはあるかと思いますが枠追加は今回厳しいです・・・

次回やる時はよろしくお願いしますm(_ _)m

**Comment by mayukojpn** [comment]
ざんねん☔️
