### ISSUE TITLE
【SP】グロナビ 高さ修正

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#155]
デザインでは45px　デザインと違うから修正

**Comment by inc2734** [comment]
PC もデザインでは 47px で高さが違うので修正してみましたがどうでしょう？

**Comment by mignonstyle** [comment]
@inc2734 ありがとうございます。フォントサイズも全然違うので、両方直してからでないと逆にバランスが悪くなってしまうので、ひとまずこのままにしておいていただけますか？
フォントサイズを直してから両方マージしていただこうかと思います。

**Comment by inc2734** [comment]
あれ、ほんとですね、すみません。なぜ 12px にしてしまったのか。issues/#155 ブランチ作業するのに邪魔だと思うので消しちゃってくださいm(_ _)m

**Comment by mignonstyle** [comment]
ありがとうございます。かえってお手数をお掛けして申し訳ありません。
ありがとうございました。
