### ISSUE TITLE
サムネイルの時間修正 13:30 - 20:00 → 13:00 - 20:00

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#168]
すみません、開催時間、私が間違えてました。
時間の表記があるものをすべて見直して修正します。

**Comment by torounit** [comment]
@mignonstyle これマージしていいですー？

**Comment by mignonstyle** [comment]
@torounit  ありがとうございます！
metaタグのOGPとTwitterのdescriptionも修正お願いできますかー？

"【京都開催】1/23（土）13：30~　WordBash Kyoto vol.1"
↓
"【京都開催】1/23（土）13:00 - 20:00　WordBash Kyoto vol.1"

**Comment by mignonstyle** [comment]
@torounit 修正ありがとうございます。マージよろしくお願いしますー

**Comment by mignonstyle** [comment]
修正済みのためFIx
