### ISSUE TITLE
お問い合わせフォームのリンク追加

### ISSUE THREAD

**Issue by contiki9** [WordBash/kyoto-vol1#169]
今の状態だと問い合わせフォームがわかりにくいとのことでどこかに、ボタンかテキストリンク追加。

■問い合わせフォームURL
https://docs.google.com/forms/d/1UQdPfKzDGxu-NOL3ZuME7gsiLdoCmMYFrQKkcwaS3Lc/viewform?edit_requested=true

**Comment by mignonstyle** [comment]
LOCATION の【会場】の下に【お問合せ】の項目を追加して入れましょうか

**Comment by contiki9** [comment]
そうしましょうか！
