### ISSUE TITLE
スピーカーのプロフィールのSNS（Twitter、FB）が抜けてるので追加

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#176]

**Comment by mignonstyle** [comment]
fa-twitter、fa-facebook-squareが反映されていなかったのでdashiconsに変更

**Comment by mignonstyle** [comment]
@inc2734 スピーカーのプロフィールのSNSアイコン、fa-twitter、fa-facebook-squareのCSSが反映されてなかったので、ひとまずフォントをdashiconsにして対処しました。
反映されなかった原因とかわかったら直していただけると助かりますー

**Comment by torounit** [comment]
@mignonstyle ちなみにこれってどんな問題です？
現状のmasterのスクリーンショットだとこんな感じです。
<img width="1189" alt="2016-01-03 16 18 35" src="https://cloud.githubusercontent.com/assets/1908815/12077699/ae17fa7a-b235-11e5-9a20-a3ae0a17e182.png">

**Comment by mignonstyle** [comment]
@torounit Chrome、Firefox（ノーマル版）だと表示されてるんですけど、Firefox Developer EditionだとTwitterとFBのアイコンが表示されてなくて。
Firefox Developer Edition（最新バージョン）のバグでしょうか？

![sns](https://cloud.githubusercontent.com/assets/7196028/12077922/76cdfa3e-b23e-11e5-954c-a0a0218ba123.png)

Firefox Developer Editionを使ってる人ってあまりいないでしょうか？
自分は使ってて、表示されないのが気になったので直しちゃったんですけど、使われてる方が少ないようでしたら今のままでもいいかもですー

**Comment by torounit** [comment]
こちらのFirefox DEの同一バージョンで表示されたので、再現性がないので、closeします。
