### ISSUE TITLE
WordBash Kyotoのサイトがサーバエラーで表示されない

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#207]
@hideokamoto 
すいません、WordBash Kyotoのサイト
http://wordbash.github.io/kyoto-vol1/ 
みようと思ったらwordbash.orgに飛ばされて「サーバーが見つかりませんでした」となって表示されないのですが、リダイレクトの設定入れたままとかになってますか？

wordbash.orgのドメインって結局どうなったんでした？

（2016年の振り返りブログでWordBash Kyotoのサイトのキャプチャ使いたかっただけなので急ぎではないです）

**Comment by hideokamoto** [comment]
リダイレクト外しました。
キャッシュ残ってるかもなので、急ぎならば以下のようにクエリストリング適当につけといてください。
https://wordbash.github.io/kyoto-vol1/?a
