### ISSUE TITLE
OGP-image用 データ作成

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#26]
メインビジュアルを元にOGP用image作る　いまい

**Comment by inc2734** [comment]
画像は作成中でしょうか？まだなら 20151222_main-image.ai のわぷーとか入れときます？

**Comment by mignonstyle** [comment]
ありがとうございます。画像作成中ですのでお待ち下さいー

**Comment by mignonstyle** [comment]
作成しましたのでお願いしますー

![ogp-thum](https://cloud.githubusercontent.com/assets/7196028/11981675/3d905888-a9e8-11e5-8c2e-f97caa618762.png)

**Comment by torounit** [comment]
@mignonstyle ご確認くださいー。

<img width="675" alt="2015-12-24 3 00 02" src="https://cloud.githubusercontent.com/assets/1908815/11981947/84fdfd5e-a9ea-11e5-893f-5d523c04547d.png">
