### ISSUE TITLE
タイムラインの歓談タイムのアイコンが src になってる

### ISSUE THREAD

**Issue by inc2734** [WordBash/kyoto-vol1#27]

**Comment by mayukojpn** [comment]
`<i class="icon--xxx">` みたいにするということですか？

**Comment by inc2734** [comment]
まだ確認できてませんが、いまgithubpageで画像が出ているなら修正済みだと思います

**Comment by inc2734** [comment]
あ、まだ修正されてなかったです！
<img src="./assets/src/images/
のようになっているところを
<img src="./assets/dest/images/
とする必要があります。
