### ISSUE TITLE
トップへもどるわぷー データ差し替え

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#29]
Bashのわぷーデータをあやかさんから貰ったらわぷーを差し替えてください

**Comment by mignonstyle** [comment]
「Topへ」のふきだしつけたaiデータをGooglドライブにUPしましたので
差し替えよろしくお願いします。
top-wapuu.ai

![top-wapuu](https://cloud.githubusercontent.com/assets/7196028/11919129/67211a2e-a78c-11e5-966f-99c0db13012a.png)

**Comment by mayukojpn** [comment]
Google ドライブに追加してください→ mayuko.jpn@gmail.com
