### ISSUE TITLE
【PC】【TB】グロナビ easingで気持ちいい動きに修正（jQuery）

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#54]
easingを入れてゆったりとした動きに

**Comment by inc2734** [comment]
マウスオーバーでメニューが上下する動きのところですよね。
いま CSS で動きをつけていて、0.2秒の ease になっています。
https://github.com/WordBash/kyoto-vol1/blob/master/assets/src/scss/objects/_global-nav.scss#L62
どの easing が良いとか、何秒の動きが良いというのはありますか？

**Comment by mignonstyle** [comment]
transition: margin 0.3s ease-in-out;
でお願いしますー。

**Comment by inc2734** [comment]
修正しました！

**Comment by mignonstyle** [comment]
ありがとうございます！こちらでOKです！よろしくお願いします！
