### ISSUE TITLE
【PC】【TB】【SP】メインビジュアル Bashロゴ差し替え CSS修正

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#55]
aiデータは受け取り済み。メインビジュアルにあわせてサイズ調整後、UPしますので、差し替えお願いします。

**Comment by mignonstyle** [comment]
PC版データをGoogleドライブにUPしましたのでよろしくお願いします。
フォントサイズやマージンに調整いれてあります。
20151222_main-image_PC.ai

**Comment by mignonstyle** [comment]
![mainimage_pc](https://cloud.githubusercontent.com/assets/7196028/11957466/455d5cf2-a905-11e5-8cc9-91ee9628d441.png)

**Comment by mignonstyle** [comment]
遅くなってすみません。TBとSPのメインビジュアルもGoogleドライブにUPしましたのでよろしくお願いします。
20151222_main-image.ai

フォントサイズやマージンをそれぞれで変えてありますので、お手数ですがよろしくお願いしますー。
SPにわぷーも入れて下さい。

**Comment by mignonstyle** [comment]
![main](https://cloud.githubusercontent.com/assets/7196028/11966537/c3973d88-a93f-11e5-8638-fec88eaa4b77.png)

**Comment by inc2734** [comment]
わぷーは PC のように移動は無しで、ロゴに被る位置でふわふわしている感じで良いですか？

**Comment by mignonstyle** [comment]
> わぷーは PC のように移動は無しで、ロゴに被る位置でふわふわしている感じで良いですか？

はい。そのようにお願いできますか。

**Comment by mignonstyle** [comment]
@inc2734  padding 方式で問題ありませんのでよろしくお願いします。

**Comment by inc2734** [comment]
@mignonstyle キャラクター入れてマージしました！確認お願いします。問題なければ issue 閉じますー

**Comment by torounit** [comment]
+1

**Comment by mignonstyle** [comment]
ありがとうございます！OKですのでよろしくお願いします！
