### ISSUE TITLE
Twitter Cardsの記述削除（訂正。WordBashのTwitter アカウントに変更）

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#64]
content="@inc2734"になってるw

**Comment by inc2734** [comment]
あ、そうなんです、ここどうしようかなと思って。シェアされたときに画像とかだしたいんですけど、Twitter アカウントないなーと…。とりあえず消しときます！

**Comment by mignonstyle** [comment]
すみません、WordBashでTwitter アカウント作る事になったので、記述は残しておいてくださいー
