### ISSUE TITLE
【PC】CONTENT部分の内容を3カラムに修正

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#65]
項目1個増えてたの気づかなかったですw
バランスが気になるので、ざっくりマージンとかいれてデザイン修正しますので、後ほどコーディングの修正お願いします。

**Comment by mignonstyle** [comment]
3カラムにしてください。よろしくお願いしますー

![contents](https://cloud.githubusercontent.com/assets/7196028/11966962/8c80e486-a942-11e5-9ba7-ebefadcd3913.png)

**Comment by contiki9** [comment]
3つのやつだけ文章多めなので3columnにするとバランス崩れたので今の形にしています…。
文章も変更しますか？

**Comment by mignonstyle** [comment]
でしたら1カラムでどうでしょうか？文章は今のままでいいと思いますー

ただ、「結構です。」が2回続けて出てくるのがちょっと気になったので、
「聞きたい話だけを聞いて頂いたり、セッションを抜けてる時は」って、続けちゃってもいいかなと思いました。ちょっとコンチさんのほうでいい感じに修正していただけますか？
