### ISSUE TITLE
html bug

### ISSUE THREAD

**Issue by torounit** [WordBash/kyoto-vol1#69]
所々、閉じタグがバグっちゃってます。ただ、タイムライン崩れとは関係ない模様。

**Comment by torounit** [comment]
#70 fixed

**Comment by inc2734** [comment]
`#container`が`#header`のすぐ後で閉じられてしまってる？

**Comment by inc2734** [comment]
`#content`の最後も`</div>`が一個多いぽい

**Comment by torounit** [comment]
いま追加修正してます。いんでんとはとりあえずまんまで。

**Comment by torounit** [comment]
travisに htmllintとか入れるべきか・・・。

**Comment by inc2734** [comment]
インデントずれてると閉じ忘れ探すのも大変なので lint で自動チェックさせれるならしたほうが楽そうですね…
