### ISSUE TITLE
fontについて

### ISSUE THREAD

**Issue by torounit** [WordBash/kyoto-vol1#78]
@mignonstyle これは游ゴシック指定なんですか？ デザインデータと雰囲気が違う気がするので、ちょっと確認です。

**Comment by inc2734** [comment]
僕がとりあえずで入れていたと気がするので変更しましょう！

**Comment by contiki9** [comment]
いいえ犯人は私です。MSゴシックが嫌だったので…多分@mignonstyleさんはメイリオ指定だった気がします

**Comment by inc2734** [comment]
20151219_wordbash-kyoto.ai だとヒラギノW3じゃないですかね？

**Comment by contiki9** [comment]
じゃあ、私の勘違いですね

**Comment by inc2734** [comment]
あ僕じゃなくてこんちさんでした^^;
https://github.com/WordBash/kyoto-vol1/commit/9216a46ff94800793317e3c70b320c564d613dd2
とりあえず游ゴシックよりヒラギノW3優先に変更しときます。

**Comment by torounit** [comment]
とりあえずmargeしますた。
