### ISSUE TITLE
［speaker］アイコンの説明追加

### ISSUE THREAD

**Issue by contiki9** [WordBash/kyoto-vol1#80]
アイコンの意味追加。
※どこかアイコンの意味の一覧みたいなページ知りませんか…

**Comment by torounit** [comment]
#23 重複してます？

**Comment by contiki9** [comment]
重複してますね…。でも対応しちゃった(_ゝω・_)

**Comment by torounit** [comment]
じゃー元のチケットもくろーずしておいてくださーい！

**Comment by torounit** [comment]
あと、インデントがすぺーすなんやで・・・・。直してー！！！
