### ISSUE TITLE
Googleマップ　PC時　「大きな地図で見る」リンク、SP時「地図アプリで見る」（アプリ起動）ボタン追加

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#91]
Googleマップの下のところに
PC、タブレット時　「大きな地図で見る」リンク
SP時「地図アプリで見る」（アプリ起動）ボタン追加を追加してください。

**Comment by mayukojpn** [comment]
やりますよー！

ところで iframe の地図に `pointer-events: none;` が指定されてて、地図中のいろんなボタンがクリック出来ないですけど、これはそのままでいいのでしょうか？？

**Comment by inc2734** [comment]
> 地図中のいろんなボタンがクリック出来ないですけど、

わー！これはダメですね。スクロールしてるときにマップがくると拡大が動いてスクロールが止まってしまうのがイヤで足したのですが、消しちゃってください

**Comment by mayukojpn** [comment]
はーい！けしちゃいます
