### ISSUE TITLE
［SP］参加ボタンの表示

### ISSUE THREAD

**Issue by contiki9** [WordBash/kyoto-vol1#92]
スマホで見るとメインビジュアルのところのボタンが表示されていない

**Comment by mignonstyle** [comment]
すみません、スマホではメインビジュアルに入りきらないので参加ボタン非表示にしてもらってます。
参加ボタンあったほうがいいですよね？どうしましょう・・・

**Comment by contiki9** [comment]
aboutWordbashの上に参加ボタンつけるのはどうでしょう？

**Comment by mignonstyle** [comment]
ひとまずその方向でお願いできますか？
できればファーストビューでメインビジュアル＆参加ボタンまで見せたいので、ちょっと考えてまたissues立てるかもです。

**Comment by mignonstyle** [comment]
メインビジュアル Bashロゴ差し替え CSS修正 #55 で
スマホにも参加ボタンつけてお願いしてるので#92はClose
