### ISSUE TITLE
［speaker］アイコンの説明 並び順とCSS修正

### ISSUE THREAD

**Issue by mignonstyle** [WordBash/kyoto-vol1#96]
並び順とCSSを修正してください（コンチさんごめんなさい！！）
念のためデザインデータをGoogleドライブにあげてあります。
20151222_speakerアイコン説明_CSS.ai

**Comment by mignonstyle** [comment]
![speaker_icon_pc](https://cloud.githubusercontent.com/assets/7196028/11957855/8d11da26-a907-11e5-852f-01dc1722016c.png)

![speaker_icon_sp](https://cloud.githubusercontent.com/assets/7196028/11957858/92b8f1e4-a907-11e5-8ff9-269a51f58584.png)

**Comment by mayukojpn** [comment]
🙆

**Comment by torounit** [comment]
@mayukojpn 森山さんやってます？

**Comment by mayukojpn** [comment]
あっいまから席はなれちゃうんで、できそうだったらやっといてもらえるとたすかります！

**Comment by torounit** [comment]
@mignonstyle ごかくにんくださいー。良ければクローズしまーす！

**Comment by mignonstyle** [comment]
@torounit ありがとうございます！こちらでOKですのでクローズしてくださいー
